"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const stores={empresas:"Empresas",contas:"Contas bancárias",centrosCusto:"Centros de custo",tiposCusto:"Tipos de custo",tiposMovimentacao:"Tipos de movimentação"};
const titles={dashboard:"Visão geral",lancamentos:"Lançamentos",cadastros:"Cadastros",relatorios:"Relatórios",backup:"Backup e dados",configuracoes:"Configurações"};
let state={entries:[],registers:{},activeRegister:"empresas",folder:null,filters:{month:new Date().toISOString().slice(0,7),company:"",account:"",search:""}};
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dateBR=v=>v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"—";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(msg){const e=$("#toast");e.textContent=msg;e.classList.add("show");clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove("show"),3200)}
async function audit(acao,detalhes={}){await DB.put("auditLogs",{id:uid(),acao,detalhes,createdAt:now()})}
async function load(){
  state.entries=await DB.all("lancamentos");
  for(const s of Object.keys(stores))state.registers[s]=await DB.all(s);
  const f=await DB.get("configuracoes","folder-handle");state.folder=f?.handle||null;
  const prefs=await DB.get("configuracoes","preferences")||{};
  $("#dark-mode").checked=!!prefs.dark;$("#compact-mode").checked=!!prefs.compact;
  document.body.classList.toggle("dark",!!prefs.dark);document.body.classList.toggle("compact",!!prefs.compact);
  renderAll();
}
function filtered(){
  return state.entries.filter(e=>(!state.filters.month||(e.competencia||e.data?.slice(0,7))===state.filters.month)&&(!state.filters.company||e.empresa===state.filters.company)&&(!state.filters.account||e.conta===state.filters.account)&&(!state.filters.search||(e.descricao||"").toLowerCase().includes(state.filters.search)));
}
function option(items,value=""){return `<option value="">— Selecione —</option>`+items.filter(x=>x.ativo!==false).sort((a,b)=>a.nome.localeCompare(b.nome)).map(x=>`<option ${x.nome===value?"selected":""}>${esc(x.nome)}</option>`).join("")}
function renderFilters(){
  $("#filter-month").value=state.filters.month;
  $("#filter-company").innerHTML=`<option value="">Todas</option>`+state.registers.empresas.map(x=>`<option ${x.nome===state.filters.company?"selected":""}>${esc(x.nome)}</option>`).join("");
  $("#filter-account").innerHTML=`<option value="">Todas</option>`+state.registers.contas.map(x=>`<option ${x.nome===state.filters.account?"selected":""}>${esc(x.nome)}</option>`).join("");
}
function status(e){if(e.status==="pago")return"pago";if(e.vencimento&&e.vencimento<new Date().toISOString().slice(0,10))return"vencido";return e.status||"pendente"}
function renderDashboard(){
  const list=filtered(),inc=list.reduce((s,e)=>s+Number(e.entrada||0),0),out=list.reduce((s,e)=>s+Number(e.saida||0),0),pending=list.filter(e=>status(e)!=="pago"),pv=pending.reduce((s,e)=>s+Number(e.saida||e.entrada||0),0);
  $("#kpi-income").textContent=money(inc);$("#kpi-expense").textContent=money(out);$("#kpi-balance").textContent=money(inc-out);$("#kpi-pending").textContent=money(pv);
  $("#kpi-income-count").textContent=`${list.filter(e=>e.entrada>0).length} lançamentos`;$("#kpi-expense-count").textContent=`${list.filter(e=>e.saida>0).length} lançamentos`;$("#kpi-overdue").textContent=`${pending.filter(e=>status(e)==="vencido").length} vencidas`;
  $("#recent-body").innerHTML=list.sort((a,b)=>b.data.localeCompare(a.data)).slice(0,7).map(e=>`<tr><td>${dateBR(e.data)}</td><td><b>${esc(e.descricao)}</b></td><td>${esc(e.empresa||"—")}</td><td>${esc(e.conta||"—")}</td><td><span class="badge ${status(e)}">${status(e)}</span></td><td class="right ${e.entrada?"amount-in":"amount-out"}">${e.entrada?money(e.entrada):"− "+money(e.saida)}</td></tr>`).join("")||`<tr><td colspan="6" class="muted">Nenhuma movimentação no período.</td></tr>`;
  const days={};list.forEach(e=>{const d=e.data?.slice(-2)||"—";days[d]??={i:0,o:0};days[d].i+=Number(e.entrada||0);days[d].o+=Number(e.saida||0)});const max=Math.max(1,...Object.values(days).flatMap(v=>[v.i,v.o]));
  $("#chart").innerHTML=Object.entries(days).sort((a,b)=>a[0]-b[0]).slice(-15).map(([d,v])=>`<div class="bar-group"><i class="bar" title="${money(v.i)}" style="height:${v.i/max*100}%"></i><i class="bar out" title="${money(v.o)}" style="height:${v.o/max*100}%"></i><span class="bar-label">${d}</span></div>`).join("")||`<p class="muted">O gráfico aparecerá após o primeiro lançamento.</p>`;
  const groups={};list.forEach(e=>{if(e.saida)groups[e.centroCusto||"Não informado"]=(groups[e.centroCusto||"Não informado"]||0)+Number(e.saida)});const gm=Math.max(1,...Object.values(groups));
  $("#breakdown").innerHTML=Object.entries(groups).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,v])=>`<div class="break-row"><span>${esc(k)}</span><div class="track"><div class="fill" style="width:${v/gm*100}%"></div></div><b class="right">${money(v)}</b></div>`).join("")||`<p class="muted">Sem saídas classificadas.</p>`;
}
function renderEntries(){
  const list=filtered().sort((a,b)=>b.data.localeCompare(a.data));
  $("#entries-body").innerHTML=list.map(e=>`<tr><td>${dateBR(e.data)}</td><td><b>${esc(e.descricao)}</b><br><small class="muted">${esc(e.conta||"")}</small></td><td>${esc(e.empresa||"—")}</td><td>${esc(e.centroCusto||e.tipoCusto||"—")}</td><td><span class="badge ${status(e)}">${status(e)}</span></td><td class="right amount-in">${e.entrada?money(e.entrada):"—"}</td><td class="right amount-out">${e.saida?money(e.saida):"—"}</td><td><button class="link-btn" data-edit="${e.id}">Editar</button> <button class="link-btn" data-delete="${e.id}">Excluir</button></td></tr>`).join("");
  $("#entries-empty").classList.toggle("hidden",list.length>0);
}
function renderRegisters(){
  $("#register-tabs").innerHTML=Object.entries(stores).map(([k,v])=>`<button class="tab ${k===state.activeRegister?"active":""}" data-register="${k}">${v}</button>`).join("");
  $("#register-body").innerHTML=(state.registers[state.activeRegister]||[]).sort((a,b)=>a.nome.localeCompare(b.nome)).map(x=>`<tr><td><b>${esc(x.nome)}</b></td><td><span class="badge">${x.ativo===false?"Inativo":"Ativo"}</span></td><td>${new Date(x.updatedAt||x.createdAt).toLocaleString("pt-BR")}</td><td class="right"><button class="link-btn" data-remove-register="${x.id}">Excluir</button></td></tr>`).join("");
}
function renderBackup(){DB.all("backupHistorico").then(h=>{const last=h.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];$("#last-backup").textContent=last?new Date(last.createdAt).toLocaleString("pt-BR"):"Nunca realizado";$("#backup-result").textContent=last?.resultado||"—"});$("#backup-count").textContent=state.entries.length;$("#folder-state").textContent=state.folder?"Configurado":("showDirectoryPicker"in window?"Não configurado":"Download manual");$("#backup-destination").textContent=state.folder?.name||"Download"}
function renderAll(){renderFilters();renderDashboard();renderEntries();renderRegisters();renderBackup()}
function showView(v){$$(".view").forEach(x=>x.classList.remove("active"));$(`#view-${v}`).classList.add("active");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#page-title").textContent=titles[v];$("#sidebar").classList.remove("open")}
function fillEntrySelects(e={}){for(const [id,s,key] of [["entry-company","empresas","empresa"],["entry-account","contas","conta"],["entry-center","centrosCusto","centroCusto"],["entry-cost","tiposCusto","tipoCusto"],["entry-movement","tiposMovimentacao","tipoMov"]])$("#"+id).innerHTML=option(state.registers[s],e[key])}
function openEntry(id){const e=state.entries.find(x=>x.id===id)||{};$("#entry-id").value=e.id||"";$("#entry-title").textContent=e.id?"Editar lançamento":"Novo lançamento";$("#entry-description").value=e.descricao||"";$("#entry-date").value=e.data||new Date().toISOString().slice(0,10);$("#entry-due").value=e.vencimento||"";$("#entry-nature").value=e.natureza||(e.saida?"saida":"entrada");$("#entry-value").value=e.entrada||e.saida||"";$("#entry-status").value=e.status||"pago";$("#entry-notes").value=e.observacoes||"";fillEntrySelects(e);$("#entry-dialog").showModal()}
async function saveEntry(ev){ev.preventDefault();const id=$("#entry-id").value||uid(),old=state.entries.find(x=>x.id===id),nature=$("#entry-nature").value,val=Number($("#entry-value").value);const e={id,descricao:$("#entry-description").value.trim(),data:$("#entry-date").value,competencia:$("#entry-date").value.slice(0,7),vencimento:$("#entry-due").value,natureza:nature,entrada:nature==="entrada"?val:0,saida:nature==="saida"?val:0,empresa:$("#entry-company").value,conta:$("#entry-account").value,centroCusto:$("#entry-center").value,tipoCusto:$("#entry-cost").value,tipoMov:$("#entry-movement").value,status:$("#entry-status").value,observacoes:$("#entry-notes").value.trim(),ativo:true,createdAt:old?.createdAt||now(),updatedAt:now()};await DB.put("lancamentos",e);await audit(old?"LANCAMENTO_ALTERADO":"LANCAMENTO_CRIADO",{id});$("#entry-dialog").close();await load();toast("Lançamento salvo com segurança.")}
async function removeEntry(id){if(!confirm("Mover este lançamento para a lixeira?"))return;const e=state.entries.find(x=>x.id===id);await DB.put("lixeira",{...e,id:"trash-"+uid(),originalId:e.id,deletedAt:now()});await DB.remove("lancamentos",id);await audit("LANCAMENTO_EXCLUIDO",{id});await load();toast("Lançamento movido para a lixeira.")}
async function saveRegister(ev){ev.preventDefault();const nome=$("#register-name").value.trim();if(!nome)return;if(state.registers[state.activeRegister].some(x=>x.nome.toLowerCase()===nome.toLowerCase()))return toast("Este cadastro já existe.");await DB.put(state.activeRegister,{id:uid(),nome,ativo:true,createdAt:now(),updatedAt:now()});$("#register-dialog").close();$("#register-name").value="";await load();toast("Cadastro salvo.")}
function exportCSV(){const rows=[["Data","Descrição","Empresa","Conta","Centro de Custo","Tipo de Custo","Tipo Movimentação","Status","Entrada","Saída"],...filtered().map(e=>[e.data,e.descricao,e.empresa,e.conta,e.centroCusto,e.tipoCusto,e.tipoMov,status(e),e.entrada,e.saida])];download(new Blob(["\ufeff"+rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n")],{type:"text/csv"}),`FinanceFlow_Lancamentos_${state.filters.month||"todos"}.csv`)}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function payload(){const data={};for(const s of DB.stores)data[s]=await DB.all(s);const base={appName:"FinanceFlow Pro",appVersion:"2.0.0",schemaVersion:1,createdAt:now(),recordCount:Object.values(data).reduce((n,v)=>n+v.length,0)};const raw=JSON.stringify(data);const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw));base.checksum=[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("");return{metadata:base,data}}
async function backup(){try{const p=await payload(),json=JSON.stringify(p,null,2),name=`FinanceFlow_Backup_${new Date().toISOString().replace("T","_").slice(0,19).replaceAll(":","-")}.json`;if(state.folder){const perm=await state.folder.queryPermission({mode:"readwrite"});if(perm!=="granted"&&await state.folder.requestPermission({mode:"readwrite"})!=="granted")throw Error("Permissão não concedida");const f=await state.folder.getFileHandle(name,{create:true}),w=await f.createWritable();await w.write(json);await w.close()}else download(new Blob([json],{type:"application/json"}),name);await DB.put("backupHistorico",{id:uid(),createdAt:now(),arquivo:name,resultado:"Sucesso",recordCount:p.metadata.recordCount,checksum:p.metadata.checksum});renderBackup();toast("Backup concluído com sucesso.")}catch(e){await DB.put("backupHistorico",{id:uid(),createdAt:now(),resultado:"Erro: "+e.message});renderBackup();toast("Não foi possível concluir o backup: "+e.message)}}
async function chooseFolder(){if(!window.showDirectoryPicker)return toast("Este navegador usa backup por download.");try{state.folder=await showDirectoryPicker({mode:"readwrite"});await DB.put("configuracoes",{id:"folder-handle",handle:state.folder,updatedAt:now()});renderBackup();toast("Pasta de backup configurada.")}catch(e){if(e.name!=="AbortError")toast("A pasta não pôde ser configurada.")}}
async function restore(file){try{const p=JSON.parse(await file.text());if(p.metadata?.appName!=="FinanceFlow Pro"||!p.data?.lancamentos)throw Error("Arquivo não reconhecido");$("#restore-preview").innerHTML=`<div class="migration-alert"><b>Backup válido:</b> ${p.metadata.recordCount} registros, criado em ${new Date(p.metadata.createdAt).toLocaleString("pt-BR")}. <button class="btn primary" id="confirm-restore">Substituir base</button></div>`;$("#confirm-restore").onclick=async()=>{if(!confirm("A base atual será copiada para um backup e depois substituída. Continuar?"))return;await backup();for(const s of DB.stores)if(Array.isArray(p.data[s])){await DB.clear(s);await DB.bulkPut(s,p.data[s])}await audit("BACKUP_RESTAURADO",{arquivo:file.name});await load();toast("Backup restaurado e validado.")}}catch(e){toast("Arquivo inválido: "+e.message)}}
async function integrity(){const list=state.entries,ids=new Set(),dup=[],invalid=[];let inc=0,out=0;list.forEach(e=>{if(ids.has(e.id))dup.push(e.id);ids.add(e.id);if(!e.id||!e.data||(!Number(e.entrada)&&!Number(e.saida)))invalid.push(e.id||"sem ID");inc+=Number(e.entrada||0);out+=Number(e.saida||0)});$("#integrity-result").innerHTML=`<article class="panel"><h3>Resultado da verificação</h3><div class="stats-list"><span>Registros <b>${list.length}</b></span><span>Entradas <b>${money(inc)}</b></span><span>Saídas <b>${money(out)}</b></span><span>Saldo <b>${money(inc-out)}</b></span><span>IDs duplicados <b>${dup.length}</b></span><span>Registros inválidos <b>${invalid.length}</b></span></div></article>`;await audit("VERIFICACAO_INTEGRIDADE",{registros:list.length,duplicados:dup.length,invalidos:invalid.length});toast("Verificação concluída.")}
async function preferences(){const p={id:"preferences",dark:$("#dark-mode").checked,compact:$("#compact-mode").checked,updatedAt:now()};await DB.put("configuracoes",p);document.body.classList.toggle("dark",p.dark);document.body.classList.toggle("compact",p.compact)}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.close)$("#"+b.dataset.close).close();if(b.dataset.view)showView(b.dataset.view);if(b.dataset.go)showView(b.dataset.go);if(b.dataset.edit)openEntry(b.dataset.edit);if(b.dataset.delete)removeEntry(b.dataset.delete);if(b.dataset.register){state.activeRegister=b.dataset.register;renderRegisters()}if(b.dataset.export!==undefined)exportCSV();if(b.dataset.removeRegister){if(confirm("Excluir este cadastro?"))DB.remove(state.activeRegister,b.dataset.removeRegister).then(load)}});
$("#nav").onclick=e=>{const b=e.target.closest("[data-view]");if(b)showView(b.dataset.view)};$("#new-entry").onclick=()=>openEntry();$("#entry-form").onsubmit=saveEntry;$("#new-register").onclick=()=>$("#register-dialog").showModal();$("#register-form").onsubmit=saveRegister;$("#export-csv").onclick=exportCSV;$("#print-report").onclick=()=>{showView("dashboard");setTimeout(print,100)};$("#run-integrity").onclick=integrity;$("#backup-now").onclick=backup;$("#quick-backup").onclick=backup;$("#choose-folder").onclick=chooseFolder;$("#test-folder").onclick=backup;$("#remove-folder").onclick=async()=>{state.folder=null;await DB.remove("configuracoes","folder-handle");renderBackup();toast("Autorização removida.")};$("#restore-file").onchange=e=>e.target.files[0]&&restore(e.target.files[0]);$("#filter-month").onchange=e=>{state.filters.month=e.target.value;renderAll()};$("#filter-company").onchange=e=>{state.filters.company=e.target.value;renderAll()};$("#filter-account").onchange=e=>{state.filters.account=e.target.value;renderAll()};$("#search").oninput=e=>{state.filters.search=e.target.value.toLowerCase();renderEntries()};$("#clear-filters").onclick=()=>{state.filters={month:"",company:"",account:"",search:""};$("#search").value="";renderAll()};$("#menu-btn").onclick=()=>$("#sidebar").classList.toggle("open");$("#dark-mode").onchange=preferences;$("#compact-mode").onchange=preferences;$("#clean-legacy").onclick=()=>{if(confirm("Remover somente a cópia legada do localStorage? A base IndexedDB será mantida.")){localStorage.removeItem("financeflow_db");localStorage.removeItem("financeflow_legacy_backup_v1");toast("Cópia legada removida.")}};
window.addEventListener("online",()=>$("#online-state").textContent="Online");window.addEventListener("offline",()=>$("#online-state").textContent="Offline disponível");
(async()=>{try{await DB.open();const m=await LegacyMigration.run();await load();if(m.status==="migrated"){const a=$("#migration-alert");a.classList.remove("hidden");a.innerHTML=`<b>Migração concluída:</b> ${m.counts.lancamentos||0} lançamentos e cadastros foram copiados para a nova base. A cópia original foi preservada.`}if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./sw.js").catch(()=>{});setTimeout(()=>$("#boot").style.display="none",350)}catch(e){$("#boot").innerHTML=`<b>Não foi possível abrir a base.</b><small>${esc(e.message)}</small>`;console.error(e)}})();
